site_name: Florin Neagu Projects & Notes
site_url: https://somelamecode.github.io/notes/
site_description: Technical notes, projects, articles, and code references
site_author: Florin Neagu
repo_url: https://github.com/SomeLameCode/notes

# Material theme
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: indigo

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

# Plugins
plugins:
  - search
  - mermaid2
  - git-revision-date
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
 

# Paths
docs_dir: docs      # folder with your Markdown content
site_dir: site      # output folder for the built HTML

# Navigation
nav:
  - Home: index.md
  - Articles:
    - Code Simple Example: articles/code-example.md
    - Content Tabs example: articles/content-tabs.md
    - Admonitions example: articles/admonitions.md
    - Diagram example: articles/diagram-examples.md
    - MkDocs Initial Setup: articles/mkdocs-setup.md
    - MkDocs Publish to Github: articles/mkdocs-site-update.md
    - MkDocs Integrate with Obsidian: articles/mkdocs-integrate-with-obsidian.md
  - Projects:
    - Overview: projects/index.md
    - Paperless-ngx: projects/paperless-ngx.md
  - Code: code/index.md
  - Notebooks: notebooks/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - pymdownx.tabbed:
      alternate_style: true      
  - admonition
  - pymdownx.details